// 墨水屏尺寸 250 x 128，实际可见 250 x 122

#define SCREEN_WIDTH 250
#define SCREEN_HEIGHT 128
#define SCREEN_PADDING 10
#define SCREEN_MARGIN_RIGHT 4

// 图标尺寸
#define ICON_STATUS_SIZE 24
#define ICON_MARGIN 5

// 状态栏宽度
#define STATUS_BAR_WIDTH (ICON_STATUS_SIZE + (ICON_MARGIN * 2))

// 图标位置
#define ICON_CONNECT_X (SCREEN_WIDTH - ICON_STATUS_SIZE - SCREEN_PADDING)
#define ICON_CONNECT_Y SCREEN_PADDING

#define ICON_COLLECTOR_X ICON_CONNECT_X
#define ICON_COLLECTOR_Y (ICON_CONNECT_Y + ICON_STATUS_SIZE + ICON_MARGIN)

// 核心显示区域
#define CORE_DISPLAY_X 0
#define CORE_DISPLAY_Y 0
#define CORE_DISPLAY_WIDTH (SCREEN_WIDTH - STATUS_BAR_WIDTH)
#define CORE_DISPLAY_HEIGHT SCREEN_HEIGHT

// 数据显示页面
#define DATA_PAGE_COMPONENT_WIDTH 72
#define DATA_PAGE_COMPONENT_HEIGHT 24
#define DATA_PAGE_COMPONENT_MARGIN 5
#define DATA_PAGE_COMPONENT_LINE_GAP 2

#define DATA_PAGE_HUMIDITY_X SCREEN_PADDING
#define DATA_PAGE_HUMIDITY_Y (SCREEN_PADDING + DATA_PAGE_COMPONENT_MARGIN * 3)

#define DATA_PAGE_TEMPERATURE_X                                                \
  (SCREEN_PADDING + DATA_PAGE_COMPONENT_WIDTH + DATA_PAGE_COMPONENT_MARGIN)
#define DATA_PAGE_TEMPERATURE_Y                                                \
  (SCREEN_PADDING + DATA_PAGE_COMPONENT_MARGIN * 3)

#define DATA_PAGE_PPM_X SCREEN_PADDING
#define DATA_PAGE_PPM_Y                                                        \
  (SCREEN_PADDING + DATA_PAGE_COMPONENT_HEIGHT * 2 +                           \
   DATA_PAGE_COMPONENT_LINE_GAP + DATA_PAGE_COMPONENT_MARGIN * 4)

// 一言
#define HITOKOTO_PAGE_CONTENT_X SCREEN_PADDING
#define HITOKOTO_PAGE_CONTENT_Y                                                \
  (SCREEN_PADDING + DATA_PAGE_COMPONENT_MARGIN * 3)

#define HITOKOTO_PAGE_CONTENT_WIDTH                                            \
  (SCREEN_WIDTH - SCREEN_PADDING * 5 - STATUS_BAR_WIDTH)
#define HITOKOTO_PAGE_CONTENT_HEIGHT (SCREEN_HEIGHT - SCREEN_PADDING * 2)

// 组件位置
#define COMPONENT_TITLE_X SCREEN_PADDING
#define COMPONENT_TITLE_Y 45

#define COMPONENT_SUBTITLE_X SCREEN_PADDING
#define COMPONENT_SUBTITLE_Y 75
