#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "C93_Bak"
#define WIFI_PASSWORD "79112167"

#define CLIENT_BLE_NAME "93_ESP32_DISPLAY"
#define SERVER_BLE_NAME "93_ESP32_COLLECTOR"

#define SERVICE_UUID "cccc"
#define SENSOR_CHAR_UUID "26a8"
#define TRIGGER_CHAR_UUID "26a9"

#endif 